# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 408ea2ee3b6970ed59996f8c81008219c7b24d9305d1257bddd2ed0120191dfbf4b95e5ba984353d77dd975b13070b5c309b4cfc3d1f3fd5e94fdeec5cabc9c5

test:
  secret_key_base: 997c4b30818fa5fe5c1c35de1823e3730a633e4b991c5b1c259f38e1e66d3246150252c6cf85217b08f1d51d0a454de3a07259214d1b0a2a9d1938b60398233c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
